version: 0.0
os: linux

files:
  - source: /
    destination: /opt/codedeploy-app
    overwrite: true

hooks:
  ApplicationStart:
    - location: application-start-hook.sh
      timeout: 300
      runas: root
