version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - sed -i 's/\r$//' application-start-hook.sh
      - chmod +x application-start-hook.sh
      - ls -al application-start-hook.sh
      - ls -al dist || true

artifacts:
  files:
    - appspec.yml
    - application-start-hook.sh
    - dist/**/*
  discard-paths: no
