version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - ng build -c production
      - echo "Build completed."
  post_build:
    commands:
      - ls -al
      - ls -al dist
      - ls -al dist/my-angular-project

artifacts:
  files:
    - 'dist/my-angular-project/**/*'
    - './appspec.yml'
    # 아래 파일이 레포에 실제로 있을 때만 유지
    - application-start-hook.sh
