version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - sed -i 's/\r$//' application-start-hook.sh
      - chmod +x application-start-hook.sh

      # 배포용 폴더 만들고 dist 결과물을 루트로 복사
      - mkdir -p deploy
      - cp -r dist/my-angular-project/* deploy/

      # appspec/hook도 deploy로 같이 넣기 (필요하면)
      - cp appspec.yml deploy/
      - cp application-start-hook.sh deploy/

      - ls -al deploy

artifacts:
  base-directory: deploy
  files:
    - '**/*'
  discard-paths: no
